Title: Page Bennett
logo: assets/ltlmef2-modified.png
description: I’m a detail-oriented, adaptive professional with a passion for complex problem-solving, continuous learning, and the growing need for safety of sensitive information in the digital age. The ever-evolving field of cybersecurity aligns with my drive to expand my knowledge and respond effectively to emerging challenges. Through strong communication, analytical thinking, and a commitment to service, I aim to help organizations strengthen security, manage risk, and safeguard the people and communities they serve. 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
