Title: Page Bennett
logo: assets/ltlmef2-modified.png
description: Detail-oriented, adaptive professional with a passion for complex problem-solving. 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
